name: Go Release

on:
    push:
        tags:
            - 'v*.*.*'  # Triggers the workflow on tag creation matching this pattern

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.22'

            - name: Set up Goreleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  version: latest
                  args: release --clean

            - name: Run Goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: goreleaser release --clean
